// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ3g7pdQWeNcIHNrbZZ6A4Nik-m3bU1wM',
    appId: '1:308515270467:web:3ae7393a6c6e734642c9f6',
    messagingSenderId: '308515270467',
    projectId: 'final-exam-adv',
    authDomain: 'final-exam-adv.firebaseapp.com',
    storageBucket: 'final-exam-adv.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW9OPCBrfIM9sWOzE37f9kzdlPVjFa2oA',
    appId: '1:308515270467:android:b9d5a3be2562bde542c9f6',
    messagingSenderId: '308515270467',
    projectId: 'final-exam-adv',
    storageBucket: 'final-exam-adv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlzwVpWNNwHT_8tvR0Gdw2ExiwxWW3JAU',
    appId: '1:308515270467:ios:31cda866ab5b87bc42c9f6',
    messagingSenderId: '308515270467',
    projectId: 'final-exam-adv',
    storageBucket: 'final-exam-adv.firebasestorage.app',
    iosBundleId: 'com.example.finalExamAdv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlzwVpWNNwHT_8tvR0Gdw2ExiwxWW3JAU',
    appId: '1:308515270467:ios:31cda866ab5b87bc42c9f6',
    messagingSenderId: '308515270467',
    projectId: 'final-exam-adv',
    storageBucket: 'final-exam-adv.firebasestorage.app',
    iosBundleId: 'com.example.finalExamAdv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ3g7pdQWeNcIHNrbZZ6A4Nik-m3bU1wM',
    appId: '1:308515270467:web:329f47b688bfb07842c9f6',
    messagingSenderId: '308515270467',
    projectId: 'final-exam-adv',
    authDomain: 'final-exam-adv.firebaseapp.com',
    storageBucket: 'final-exam-adv.firebasestorage.app',
  );
}
